
# config/zed2i_yaml
# Parameters for Stereolabs ZED2i camera
---
/**:
    ros__parameters:
        general:
            camera_model: 'zed2i'
            camera_name: 'zed2i' # usually overwritten by launch file
            grab_resolution: 'HD720' # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
            grab_frame_rate: 30 # ZED SDK internal grabbing rate

        depth:
            min_depth: 0.3 # Min: 0.3, Max: 3.0
            max_depth: 10.0 # Max: 40.0
        
        sensors:
            enable_imu: true # Enable the IMU sensor
            enable_imu_fusion: true # Enable IMU fusion (for odometry and pose estimation)

        video:
            rgb_topic: '/zed2i/rgb/image_raw' # Topic name for RGB stream
            enable_rgb: true # Enable the RGB image stream
            rgb_frame_rate: 30 # Frame rate for RGB image

        positional_tracking:
            enable_pose: true # Enable positional tracking using the IMU
       
